//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.20 at 10:27:56 AM UZT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "github.com/isa/soap-demo", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.github.isa.soap_demo;
